import { Assert } from "./assert";
import { MalformedExpressionException } from "./discrimination";
import { DFAAccepts } from "./dfa";

declare const emailDisc: unique symbol;
/**
 * A nominal string type for emails
 */
export type Email = string & {
  readonly [emailDisc]: unique symbol;
};

export class InvalidEmailException extends MalformedExpressionException {}

export namespace Email {
  /**
   * RFC 5322 email validation
   * * https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression
   * * https://stackoverflow.com/a/201378/6698132
   * * https://emailregex.com/
   * * https://www.ietf.org/rfc/rfc5322.txt
   * @warn Not very restrictive; only checks syntax
   * @see [[`IsEmail`]] for a compile-time analogue
   */
  export const roughValidate = (str: string): str is Email => {
    return /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+))/.test(
      str
    );
  };

  /**
   * Assert using RFC 5322 email validation
   * @throws {@linkcode InvalidEmailException}
   * @warn Not restrictive; see {@linkcode roughValidate}
   */
  export const roughAssert = (str: string): asserts str is Email => {
    Assert(roughValidate(str), InvalidEmailException);
  };
}

/**
 * RFC 5322 email validation
 * * https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression
 * * https://stackoverflow.com/a/201378/6698132
 * * https://emailregex.com/
 * * https://www.ietf.org/rfc/rfc5322.txt
 * @warn Not very restrictive; only checks syntax
 * @see [[`Email`]] for a run-time analogue
 *
 * Generated with
 * * https://glitch.com/~efficacious-valley-repair
 * * https://github.com/AnyhowStep/efficacious-valley-repair/tree/main/app
 */
interface EmailDFA {
  startState: "0";
  acceptStates: "18" | "36" | "42";
  transitions: {
    "0": Record<'"', "1"> &
      Record<
        | "!"
        | "#"
        | "$"
        | "%"
        | "&"
        | "'"
        | "*"
        | "+"
        | "-"
        | "/"
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "="
        | "?"
        | "^"
        | "_"
        | "`"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z"
        | "{"
        | "|"
        | "}"
        | "~",
        "6"
      > &
      Record<string, "fail">;
    "1": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | "!"
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "]"
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "1"
    > &
      Record<'"', "4"> &
      Record<"\\", "5"> &
      Record<string, "fail">;
    "2": Record<
      | "!"
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "*"
      | "+"
      | "-"
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "="
      | "?"
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~",
      "6"
    > &
      Record<string, "fail">;
    "3": Record<"[", "7"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "10"
      > &
      Record<string, "fail">;
    "4": Record<"@", "3"> & Record<string, "fail">;
    "5": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\t"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | " "
      | "!"
      | '"'
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "\\"
      | "]"
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "1"
    > &
      Record<string, "fail">;
    "6": Record<".", "2"> &
      Record<"@", "3"> &
      Record<
        | "!"
        | "#"
        | "$"
        | "%"
        | "&"
        | "'"
        | "*"
        | "+"
        | "-"
        | "/"
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "="
        | "?"
        | "^"
        | "_"
        | "`"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z"
        | "{"
        | "|"
        | "}"
        | "~",
        "6"
      > &
      Record<string, "fail">;
    "7": Record<"0" | "1", "11"> &
      Record<"2", "12"> &
      Record<"3" | "4" | "5" | "6" | "7" | "8" | "9", "14"> &
      Record<string, "fail">;
    "8": Record<"-", "8"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "10"
      > &
      Record<string, "fail">;
    "9": Record<
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z",
      "18"
    > &
      Record<string, "fail">;
    "10": Record<"-", "8"> &
      Record<".", "9"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "10"
      > &
      Record<string, "fail">;
    "11": Record<".", "13"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "14"> &
      Record<string, "fail">;
    "12": Record<".", "13"> &
      Record<"0" | "1" | "2" | "3" | "4", "14"> &
      Record<"5", "15"> &
      Record<"6" | "7" | "8" | "9", "16"> &
      Record<string, "fail">;
    "13": Record<"0" | "1", "19"> &
      Record<"2", "20"> &
      Record<"3" | "4" | "5" | "6" | "7" | "8" | "9", "22"> &
      Record<string, "fail">;
    "14": Record<".", "13"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "16"> &
      Record<string, "fail">;
    "15": Record<".", "13"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5", "16"> &
      Record<string, "fail">;
    "16": Record<".", "13"> & Record<string, "fail">;
    "17": Record<"-", "17"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "18"
      > &
      Record<string, "fail">;
    "18": Record<".", "9"> &
      Record<"-", "17"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "18"
      > &
      Record<string, "fail">;
    "19": Record<".", "21"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "22"> &
      Record<string, "fail">;
    "20": Record<".", "21"> &
      Record<"0" | "1" | "2" | "3" | "4", "22"> &
      Record<"5", "23"> &
      Record<"6" | "7" | "8" | "9", "24"> &
      Record<string, "fail">;
    "21": Record<"0" | "1", "25"> &
      Record<"2", "26"> &
      Record<"3" | "4" | "5" | "6" | "7" | "8" | "9", "28"> &
      Record<string, "fail">;
    "22": Record<".", "21"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "24"> &
      Record<string, "fail">;
    "23": Record<".", "21"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5", "24"> &
      Record<string, "fail">;
    "24": Record<".", "21"> & Record<string, "fail">;
    "25": Record<".", "27"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "28"> &
      Record<string, "fail">;
    "26": Record<".", "27"> &
      Record<"0" | "1" | "2" | "3" | "4", "28"> &
      Record<"5", "29"> &
      Record<"6" | "7" | "8" | "9", "30"> &
      Record<string, "fail">;
    "27": Record<"-", "31"> &
      Record<"0" | "1", "32"> &
      Record<"2", "33"> &
      Record<
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<"3" | "4" | "5" | "6" | "7" | "8" | "9", "37"> &
      Record<string, "fail">;
    "28": Record<".", "27"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "30"> &
      Record<string, "fail">;
    "29": Record<".", "27"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5", "30"> &
      Record<string, "fail">;
    "30": Record<".", "27"> & Record<string, "fail">;
    "31": Record<"-", "31"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<string, "fail">;
    "32": Record<"-", "31"> &
      Record<
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<"]", "36"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "37"> &
      Record<string, "fail">;
    "33": Record<"-", "31"> &
      Record<
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<"]", "36"> &
      Record<"0" | "1" | "2" | "3" | "4", "37"> &
      Record<"5", "38"> &
      Record<"6" | "7" | "8" | "9", "39"> &
      Record<string, "fail">;
    "34": Record<"-", "31"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<string, "fail">;
    "35": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | "!"
      | '"'
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "]"
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "40"
    > &
      Record<"\\", "41"> &
      Record<string, "fail">;
    "36": Record<string, "fail">;
    "37": Record<"-", "31"> &
      Record<
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<"]", "36"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9", "39"> &
      Record<string, "fail">;
    "38": Record<"-", "31"> &
      Record<
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<"]", "36"> &
      Record<"0" | "1" | "2" | "3" | "4" | "5", "39"> &
      Record<string, "fail">;
    "39": Record<"-", "31"> &
      Record<
        | "0"
        | "1"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "a"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "h"
        | "i"
        | "j"
        | "k"
        | "l"
        | "m"
        | "n"
        | "o"
        | "p"
        | "q"
        | "r"
        | "s"
        | "t"
        | "u"
        | "v"
        | "w"
        | "x"
        | "y"
        | "z",
        "34"
      > &
      Record<":", "35"> &
      Record<"]", "36"> &
      Record<string, "fail">;
    "40": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | "!"
      | '"'
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "40"
    > &
      Record<"\\", "41"> &
      Record<"]", "42"> &
      Record<string, "fail">;
    "41": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\t"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | " "
      | "!"
      | '"'
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "40"
    > &
      Record<"\\", "41"> &
      Record<"]", "42"> &
      Record<string, "fail">;
    "42": Record<
      | "\u0001"
      | "\u0002"
      | "\u0003"
      | "\u0004"
      | "\u0005"
      | "\u0006"
      | "\u0007"
      | "\b"
      | "\u000b"
      | "\f"
      | "\u000e"
      | "\u000f"
      | "\u0010"
      | "\u0011"
      | "\u0012"
      | "\u0013"
      | "\u0014"
      | "\u0015"
      | "\u0016"
      | "\u0017"
      | "\u0018"
      | "\u0019"
      | "\u001a"
      | "\u001b"
      | "\u001c"
      | "\u001d"
      | "\u001e"
      | "\u001f"
      | "!"
      | '"'
      | "#"
      | "$"
      | "%"
      | "&"
      | "'"
      | "("
      | ")"
      | "*"
      | "+"
      | ","
      | "-"
      | "."
      | "/"
      | "0"
      | "1"
      | "2"
      | "3"
      | "4"
      | "5"
      | "6"
      | "7"
      | "8"
      | "9"
      | ":"
      | ";"
      | "<"
      | "="
      | ">"
      | "?"
      | "@"
      | "A"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
      | "H"
      | "I"
      | "J"
      | "K"
      | "L"
      | "M"
      | "N"
      | "O"
      | "P"
      | "Q"
      | "R"
      | "S"
      | "T"
      | "U"
      | "V"
      | "W"
      | "X"
      | "Y"
      | "Z"
      | "["
      | "^"
      | "_"
      | "`"
      | "a"
      | "b"
      | "c"
      | "d"
      | "e"
      | "f"
      | "g"
      | "h"
      | "i"
      | "j"
      | "k"
      | "l"
      | "m"
      | "n"
      | "o"
      | "p"
      | "q"
      | "r"
      | "s"
      | "t"
      | "u"
      | "v"
      | "w"
      | "x"
      | "y"
      | "z"
      | "{"
      | "|"
      | "}"
      | "~"
      | "",
      "40"
    > &
      Record<"\\", "41"> &
      Record<"]", "42"> &
      Record<string, "fail">;
    fail: Record<string, "fail">;
  };
}

/**
 * RFC 5322 email validation
 * * https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression
 * * https://stackoverflow.com/a/201378/6698132
 * * https://emailregex.com/
 * * https://www.ietf.org/rfc/rfc5322.txt
 * @warn Not very restrictive; only checks syntax
 * @see [[`Email`]] for a run-time analogue
 */
export type IsEmail<T extends string> = DFAAccepts<EmailDFA, T>;
